# Cargo configuration for StarRocks Admin Backend

# Default clippy flags for local development
# To enforce strict checks (like in CI), use:
# cargo clippy --all-targets -- --deny warnings --allow clippy::uninlined-format-args
[alias]
clippy-strict = "clippy --all-targets -- --deny warnings --allow clippy::uninlined-format-args"
clippy-fix = "clippy --fix --all-targets --allow-dirty --allow-staged --allow-no-vcs -- --deny warnings --allow clippy::uninlined-format-args"

