# Cargo 配置文件 - 开发环境优化
# 优化编译性能和增量编译

[build]
# 使用增量编译
incremental = true

# 并行编译
jobs = 4

# 目标目录
target-dir = "target"

[target.x86_64-unknown-linux-gnu]
# 链接器优化
linker = "clang"

[profile.dev]
# 开发模式优化
opt-level = 0
debug = true
split-debuginfo = "unpacked"
incremental = true

# 减少编译时间
codegen-units = 1

[profile.dev.package."*"]
# 第三方库使用更高级别的优化
opt-level = 1

[profile.release]
# 发布模式优化
opt-level = 3
debug = false
lto = "thin"
codegen-units = 1
panic = "abort"

[profile.release.package."*"]
# 所有依赖都使用最高优化
opt-level = 3

# 网络配置
[net]
retry = 2
git-fetch-with-cli = true

# 注册表配置
[registries.crates-io]
protocol = "sparse"