apiVersion: v1
kind: Service
metadata:
  name: starrocks-admin
  namespace: starrocks-admin
spec:
  selector:
    app: starrocks-admin
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
