apiVersion: apps/v1
kind: Deployment
metadata:
  name: starrocks-admin-frontend
  namespace: starrocks-admin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: starrocks-admin-frontend
  template:
    metadata:
      labels:
        app: starrocks-admin-frontend
    spec:
      containers:
      - name: frontend
        image: starrocks-admin-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
